#!/bin/sh

read_rules() {
    filename="$1"
    while read -r rule; do
        case "${rule}" in
            '#'*)
                ;;
            '')
                ;;
            *)
                echo "${rule}"
        esac
    done < "${filename}"
}

normalize() {
    rule="$1"
    while IFS='=' read -r option value; do
        case $value in
            n)
                echo "# CONFIG_${option} is not set"
                ;;
            *)
                echo "CONFIG_${option}=${value}"
                ;;
        esac
    done
}

check_kernel() {
    rule="$1"
    grep -q "${rule}" kernel/.config
    if [ $? != 0 ]; then
        echo "${rule}"
    fi
}

for filename in rules/*; do
    read_rules "${filename}" \
        | normalize \
        | check_kernel
done
